Update node.js.yml

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -86,84 +86,84 @@ jobs:
       #     path: .scannerwork/
 
 
-  run-integration-tests:
-    runs-on: ubuntu-latest
-    needs: build_and_test
+  # run-integration-tests:
+  #   runs-on: ubuntu-latest
+  #   needs: build_and_test
 
-    strategy:
-      fail-fast: false 
-      matrix:
-        containers: [1] # Use 1 instance
+  #   strategy:
+  #     fail-fast: false 
+  #     matrix:
+  #       containers: [1] # Use 1 instance
 
-    steps:
+  #   steps:
 
-     - name: Checkout code and set up Node.js
-       uses: actions/checkout@v4
-       with:
-        fetch-depth: 0
+  #    - name: Checkout code and set up Node.js
+  #      uses: actions/checkout@v4
+  #      with:
+  #       fetch-depth: 0
 
-     - uses: actions/setup-node@v4
-       with:
-         node-version: '20.x'
-         cache: 'yarn'
+  #    - uses: actions/setup-node@v4
+  #      with:
+  #        node-version: '20.x'
+  #        cache: 'yarn'
 
-     - name: Install dependencies
-       run: yarn install --frozen-lockfile
+  #    - name: Install dependencies
+  #      run: yarn install --frozen-lockfile
 
-     - name: Build the project
-       run: yarn build
+  #    - name: Build the project
+  #      run: yarn build
 
-     - name: Set up Docker Buildx
-       uses: docker/setup-buildx-action@v2
+  #    - name: Set up Docker Buildx
+  #      uses: docker/setup-buildx-action@v2
 
-     - name: Cache Docker layers
-       uses: actions/cache@v4
-       with:
-         path: /tmp/.buildx-cache
-         key: ${{ runner.os }}-buildx-${{ hashFiles('Dockerfile.mysql') }}
-         restore-keys: |
-           ${{ runner.os }}-buildx-
+  #    - name: Cache Docker layers
+  #      uses: actions/cache@v4
+  #      with:
+  #        path: /tmp/.buildx-cache
+  #        key: ${{ runner.os }}-buildx-${{ hashFiles('Dockerfile.mysql') }}
+  #        restore-keys: |
+  #          ${{ runner.os }}-buildx-
 
-     - name: Build MySQL Docker image
-       run: |
-         docker buildx build --cache-from=type=local,src=/tmp/.buildx-cache --cache-to=type=local,dest=/tmp/.buildx-cache --output=type=docker -t my-mysql -f Dockerfile.mysql .
+  #    - name: Build MySQL Docker image
+  #      run: |
+  #        docker buildx build --cache-from=type=local,src=/tmp/.buildx-cache --cache-to=type=local,dest=/tmp/.buildx-cache --output=type=docker -t my-mysql -f Dockerfile.mysql .
 
-     - name: Run MySQL container
-       run: |
-         docker run -d --name mysql -e MYSQL_ROOT_PASSWORD=admin -e MYSQL_DATABASE=db -e MYSQL_USER=admin -e MYSQL_PASSWORD=admin -p 3306:3306 my-mysql
+  #    - name: Run MySQL container
+  #      run: |
+  #        docker run -d --name mysql -e MYSQL_ROOT_PASSWORD=admin -e MYSQL_DATABASE=db -e MYSQL_USER=admin -e MYSQL_PASSWORD=admin -p 3306:3306 my-mysql
              
-     - name: Wait for MySQL
-       run: |
-         while ! docker exec mysql mysqladmin ping -h"localhost" --silent; do
-           sleep 1
-         done
+  #    - name: Wait for MySQL
+  #      run: |
+  #        while ! docker exec mysql mysqladmin ping -h"localhost" --silent; do
+  #          sleep 1
+  #        done
 
-     - name: Run E2E tests
-       run: yarn test:e2e --detectOpenHandles --forceExit
+  #    - name: Run E2E tests
+  #      run: yarn test:e2e --detectOpenHandles --forceExit
 
-     - name: Run Integration tests
-       run: yarn test:integration --detectOpenHandles --forceExit
+  #    - name: Run Integration tests
+  #      run: yarn test:integration --detectOpenHandles --forceExit
 
-     - name: Publish E2E tests results
-       uses: actions/upload-artifact@v4
-       with:
-         name: e2e-tests-results
-         path: test-results/e2e
+  #    - name: Publish E2E tests results
+  #      uses: actions/upload-artifact@v4
+  #      with:
+  #        name: e2e-tests-results
+  #        path: test-results/e2e
 
-     - name: Publish integration tests results
-       uses: actions/upload-artifact@v4
-       with:
-         name: integration-tests-results
-         path: test-results/integration
+  #    - name: Publish integration tests results
+  #      uses: actions/upload-artifact@v4
+  #      with:
+  #        name: integration-tests-results
+  #        path: test-results/integration
 
-     - name: Publish integration tests coverage results
-       uses: actions/upload-artifact@v4
-       with:
-         name: integration-coverage-results
-         path: coverage/integration
+  #    - name: Publish integration tests coverage results
+  #      uses: actions/upload-artifact@v4
+  #      with:
+  #        name: integration-coverage-results
+  #        path: coverage/integration
 
-     - name: Stop and remove MySQL container
-       if: always()
-       run: |
-         docker stop mysql
-         docker rm mysql
+  #    - name: Stop and remove MySQL container
+  #      if: always()
+  #      run: |
+  #        docker stop mysql
+  #        docker rm mysql
